"""Feature-tour registry: every web-facing item since the MVP, backfilled.

Each entry points at exactly where it is visible in the UI
(page path + element anchor). The /tour catalog and the guided
?tour=<id> banner are both driven by ENTRIES, so a shipped item
with no tour target is a visible gap, not a silent one.
"""

# kind: "mvp" (original loop), "feature" (new capability),
# "improvement" (existing surface made better).
# path may use {mid} (latest module id) and {lesson} (its first
# lesson anchor, e.g. "lesson-add") for module-detail targets.
ENTRIES = [
    # -- MVP baseline: the original learning loop --
    {"id": "due-queue", "kind": "mvp", "title": "Spaced review queue",
     "blurb": "One card at a time, most overdue first. This is the loop.",
     "path": "/due", "anchor": "queue"},
    {"id": "module-library", "kind": "mvp", "title": "Module library",
     "blurb": "Every agent session as a lesson card with owned-progress bars.",
     "path": "/modules", "anchor": "library"},
    {"id": "concept-lessons", "kind": "mvp", "title": "Leveled explainers",
     "blurb": "Each concept explains itself three ways: plain, practitioner, expert.",
     "path": "/modules/{mid}", "anchor": "{lesson}"},
    {"id": "exercise-widgets", "kind": "mvp", "title": "Exercise widgets",
     "blurb": "Parsons drag-and-drop, fill-in blanks, predict-the-output and more.",
     "path": "/modules/{mid}", "anchor": "practice"},
    {"id": "attempt-history", "kind": "mvp", "title": "Attempt history",
     "blurb": "Every try recorded with grade, confidence and timestamp.",
     "path": "/reviews", "anchor": "attempts"},
    {"id": "result-screen", "kind": "mvp", "title": "Honest result screen",
     "blurb": "Answer any card: verdict, feedback, next-due — then back where you came from.",
     "path": "/due", "anchor": "up-next"},
    {"id": "calibration-coach", "kind": "mvp", "title": "Calibration coach",
     "blurb": "Accuracy vs confidence per skill; nudges your overconfident blind spots.",
     "path": "/reviews", "anchor": "calibration"},
    {"id": "mcp-endpoint", "kind": "mvp", "title": "MCP endpoint",
     "blurb": "Agents file learning modules with create_learning_module.",
     "path": "/status", "anchor": "status-mcp"},
    # -- Improvements: the Batch 1 ten --
    {"id": "nav-counts", "kind": "improvement", "title": "Nav badge counts",
     "blurb": "Due, Modules and History counts live in the nav — no guessing.",
     "path": "/", "anchor": "sitenav"},
    {"id": "resume-links", "kind": "improvement", "title": "Resume links",
     "blurb": "Each module card jumps straight to its first unowned lesson.",
     "path": "/modules", "anchor": "resume"},
    {"id": "queue-position", "kind": "improvement", "title": "Queue position",
     "blurb": "Card i of n plus an Up-next tag on the first card.",
     "path": "/due", "anchor": "up-next"},
    {"id": "difficulty-dots", "kind": "improvement", "title": "Difficulty dots",
     "blurb": "Five-dot FSRS difficulty meter on every card. Hover for the number.",
     "path": "/due", "anchor": "difficulty"},
    {"id": "confidence-pills", "kind": "improvement", "title": "Confidence pills",
     "blurb": "Rate 1–5 confidence with every answer; powers the calibration coach.",
     "path": "/due", "anchor": "confidence"},
    {"id": "ctrl-enter", "kind": "improvement", "title": "Ctrl+Enter to submit",
     "blurb": "Submit from any text field with Ctrl/Cmd+Enter. Try it in the box below.",
     "path": "/due", "anchor": "up-next"},
    {"id": "copy-buttons", "kind": "improvement", "title": "Copy buttons",
     "blurb": "Every code block grows a Copy button. Try one in the lesson below.",
     "path": "/modules/{mid}", "anchor": "{lesson}"},
    {"id": "answer-drafts", "kind": "improvement", "title": "Answer drafts",
     "blurb": "Type an answer, reload the page — your text survives. Cleared on submit.",
     "path": "/due", "anchor": "up-next"},
    {"id": "give-up", "kind": "improvement", "title": "Give-up path",
     "blurb": "Stuck? Give up shows the answer and records the lapse honestly.",
     "path": "/due", "anchor": "giveup"},
    {"id": "due-why", "kind": "improvement", "title": "Due-why tooltips",
     "blurb": "Hover why-due: memory strength, days overdue, lapse count.",
     "path": "/due", "anchor": "due-why"},
    # -- Features: the Batch 1 ten --
    {"id": "projects-landing", "kind": "feature", "title": "Projects landing",
     "blurb": "Every repo you are learning, with owned progress — the front door.",
     "path": "/", "anchor": "projects"},
    {"id": "debt-meter", "kind": "feature", "title": "Comprehension debt meter",
     "blurb": "What changed versus what you can prove you own, per repo and file.",
     "path": "/debt", "anchor": "debt-meter"},
    {"id": "diagnose-page", "kind": "feature", "title": "Traceback diagnose page",
     "blurb": "Paste a crash; every function it names links to its lesson.",
     "path": "/diagnose", "anchor": "diagnose-form"},
    {"id": "bloom-ladder", "kind": "feature", "title": "Bloom ladder",
     "blurb": "Six rungs beside each concept; lit rungs mark demonstrated skill tiers.",
     "path": "/modules/{mid}", "anchor": "ladder"},
    {"id": "coverage-timeline", "kind": "feature", "title": "Coverage timeline",
     "blurb": "Every session, what it made, and what stuck.",
     "path": "/reviews", "anchor": "coverage"},
    {"id": "anki-export", "kind": "feature", "title": "Anki export",
     "blurb": "All cards as tab-separated import: front, back, tags.",
     "path": "/modules", "anchor": "exports"},
    {"id": "rss-feed", "kind": "feature", "title": "RSS feed",
     "blurb": "Learning modules as RSS 2.0 for external readers.",
     "path": "/modules", "anchor": "exports"},
    {"id": "module-sharing", "kind": "feature", "title": "Module sharing",
     "blurb": "Export a module to JSON, import it into any Groundwork DB. Reviews stay private.",
     "path": "/status", "anchor": "status-share"},
    {"id": "cli-review", "kind": "feature", "title": "CLI review",
     "blurb": "python3 -m groundwork review — the queue without a browser.",
     "path": "/status", "anchor": "status-cli"},
    {"id": "ci-workflow", "kind": "feature", "title": "CI workflow",
     "blurb": "Tests run on every push; status surfaced below.",
     "path": "/status", "anchor": "status-ci"},
    {"id": "precommit-hook", "kind": "feature", "title": "Pre-commit hook",
     "blurb": "hooks/pre-commit keeps bad commits out; presence shown below.",
     "path": "/status", "anchor": "status-hooks"},
    {"id": "docstring-type", "kind": "feature", "title": "Write-the-docstring exercises",
     "blurb": "Docstring exercise cards render an explanation box. Answer one below.",
     "path": "/due", "anchor": "up-next"},
    # -- Batch 2: Groundwork itself as a learnable project, plus ten more --
    {"id": "seed-modules", "kind": "feature", "title": "Groundwork seed",
     "blurb": "Groundwork itself ships as learnable modules: export one repo's modules to a seed file, import it anywhere.",
     "path": "/status", "anchor": "status-seed"},
    {"id": "relative-times", "kind": "improvement", "title": "Relative timestamps",
     "blurb": "History reads as “just now” and “3h ago” — hover any time for the exact timestamp.",
     "path": "/reviews", "anchor": "timestamps"},
    {"id": "memory-strength", "kind": "improvement", "title": "Memory-strength bars",
     "blurb": "Each Due card shows its FSRS memory strength in days, as a bar.",
     "path": "/due", "anchor": "memory"},
    {"id": "module-sort", "kind": "improvement", "title": "Module sorting",
     "blurb": "The Modules library toggles newest-first and oldest-first.",
     "path": "/modules", "anchor": "sort"},
    {"id": "snooze-card", "kind": "improvement", "title": "Snooze a card",
     "blurb": "Not today? Snooze pushes one card to tomorrow — no grade recorded.",
     "path": "/due", "anchor": "snooze"},
    {"id": "back-to-top", "kind": "improvement", "title": "Back-to-top link",
     "blurb": "Long module pages grow a floating Back to top link.",
     "path": "/modules", "anchor": "top"},
    {"id": "sitemap-robots", "kind": "feature", "title": "Sitemap and robots",
     "blurb": "Every page and module listed for crawlers; see the live map below.",
     "path": "/status", "anchor": "status-sitemap"},
    {"id": "week-review", "kind": "feature", "title": "Week in review",
     "blurb": "Attempts, active days and pass rate for the last 7 days — a weekly ritual.",
     "path": "/reviews", "anchor": "week"},
    {"id": "reviews-csv", "kind": "feature", "title": "Review-log CSV export",
     "blurb": "Every attempt as CSV for personal analysis — grades, confidence, answers.",
     "path": "/status", "anchor": "status-csv"},
    {"id": "readonly-api", "kind": "feature", "title": "Read-only modules API",
     "blurb": "Modules with concept and card counts as JSON, for dashboards.",
     "path": "/status", "anchor": "status-api"},
    {"id": "due-api", "kind": "feature", "title": "Read-only due-queue API",
     "blurb": "The live due queue as JSON — same order as the Due page.",
     "path": "/status", "anchor": "status-api-due"},
    # -- Batch 3: same rhythm, plus the modularity rule --
    {"id": "module-health", "kind": "feature", "title": "Module health",
     "blurb": "Every capability area with its size and ceiling — web.py never grows.",
     "path": "/status", "anchor": "status-modular"},
    {"id": "due-forecast", "kind": "improvement", "title": "Next-gap forecast",
     "blurb": "Each Due card estimates its next gap at steady passes.",
     "path": "/due", "anchor": "forecast"},
    {"id": "queue-chips", "kind": "improvement", "title": "Queue status chips",
     "blurb": "Due, overdue and new cards carry distinct chips in the queue.",
     "path": "/due", "anchor": "queue-status"},
    {"id": "grading-how", "kind": "improvement", "title": "Grading disclosures",
     "blurb": "Every card says how it is judged before you answer.",
     "path": "/due", "anchor": "grading"},
    {"id": "grade-disputes", "kind": "feature", "title": "Grade disputes",
     "blurb": "Flag a wrong reference with one click; maintainers triage the queue.",
     "path": "/status", "anchor": "status-disputes"},
    {"id": "workload-graph", "kind": "feature", "title": "Workload forecast",
     "blurb": "Reviews due per day for the next 30 days — see busy days coming.",
     "path": "/reviews", "anchor": "workload"},
    {"id": "read-times", "kind": "improvement", "title": "Lesson read times",
     "blurb": "The module table of contents estimates minutes per lesson.",
     "path": "/modules/{mid}", "anchor": "readtime"},
    {"id": "module-reset", "kind": "feature", "title": "Module reset",
     "blurb": "Start a module over from a confirm page — lessons stay, progress goes.",
     "path": "/modules/{mid}", "anchor": "reset"},
    {"id": "style-guide", "kind": "feature", "title": "Component gallery",
     "blurb": "Every UI building block on one dev page, with class names.",
     "path": "/styleguide", "anchor": "styleguide"},
    {"id": "shortcuts-cheatsheet", "kind": "improvement", "title": "Keyboard shortcuts",
     "blurb": "g then d jumps to Due, ? opens the cheat sheet — typing never hijacked.",
     "path": "/", "anchor": "shortcuts"},
    {"id": "storage-meter", "kind": "feature", "title": "Storage meter",
     "blurb": "Database size and per-module rows — growth never surprises.",
     "path": "/status", "anchor": "status-storage"},
    # -- Batch 4: ten improvements + ten features, no downsizing --
    {"id": "skip-links", "kind": "improvement", "title": "Skip links",
     "blurb": "Skip to content link plus header/nav/main/footer landmarks.",
     "path": "/", "anchor": "main"},
    {"id": "pretty-404", "kind": "improvement", "title": "Helpful 404",
     "blurb": "Unknown paths get links and a project search, never a bare error.",
     "path": "/404", "anchor": "not-found"},
    {"id": "queue-groups", "kind": "improvement", "title": "Queue grouped by module",
     "blurb": "Due cards gather under collapsible per-module sections.",
     "path": "/due", "anchor": "queue-groups"},
    {"id": "daily-digest", "kind": "improvement", "title": "Daily digest",
     "blurb": "Today at a glance: due now, new cards, and where to start.",
     "path": "/due", "anchor": "digest"},
    {"id": "month-review", "kind": "improvement", "title": "Month in review",
     "blurb": "Concepts owned, accuracy trend and effort across the last 30 days.",
     "path": "/reviews", "anchor": "month"},
    {"id": "related-modules", "kind": "improvement", "title": "Related modules",
     "blurb": "Same repo or shared concepts — keep following the thread.",
     "path": "/modules/{mid}", "anchor": "related"},
    {"id": "decision-quotes", "kind": "improvement", "title": "Decision quotes",
     "blurb": "Agent chose-X-over-Y rationale quoted inside the lesson it shaped.",
     "path": "/modules/{mid}", "anchor": "decisions"},
    {"id": "clarity-votes", "kind": "improvement", "title": "Clarity votes",
     "blurb": "Rate each lesson 1–5; averages feed generation quality.",
     "path": "/modules/{mid}", "anchor": "clarity"},
    {"id": "already-know", "kind": "improvement", "title": "Already-know skip",
     "blurb": "Know it? Skip the line — the cards verify you in 30 days.",
     "path": "/modules/{mid}", "anchor": "already-know"},
    {"id": "undo-review", "kind": "improvement", "title": "Undo last review",
     "blurb": "Misclick recovery within 60 seconds — scheduling restored.",
     "path": "/reviews", "anchor": "undo"},
    {"id": "north-star", "kind": "feature", "title": "North-star dashboard",
     "blurb": "Delayed accuracy on mature cards — the number that matters.",
     "path": "/status", "anchor": "status-northstar"},
    {"id": "data-download", "kind": "feature", "title": "Personal data download",
     "blurb": "Everything about you in one JSON — portable, private.",
     "path": "/status", "anchor": "status-data"},
    {"id": "journal", "kind": "feature", "title": "Metacognition journal",
     "blurb": "Weekly what-did-you-misjudge prompt, answered privately.",
     "path": "/journal", "anchor": "journal"},
    {"id": "one-card", "kind": "feature", "title": "Just-one-card mode",
     "blurb": "Low energy? Answer a single card — no guilt design.",
     "path": "/due", "anchor": "one-card"},
    {"id": "readme-badge", "kind": "feature", "title": "README badge",
     "blurb": "Your live owned count as an embeddable SVG shield.",
     "path": "/status", "anchor": "status-badge"},
    {"id": "tool-analytics", "kind": "feature", "title": "Tool-call analytics",
     "blurb": "Which MCP tools fire, with failure rates and latency.",
     "path": "/status", "anchor": "status-tools"},
    {"id": "weekly-letter", "kind": "feature", "title": "Weekly letter",
     "blurb": "An auto-drafted private progress note — gentle, never streaky.",
     "path": "/status", "anchor": "status-letter"},
    {"id": "serendipity", "kind": "feature", "title": "Serendipity cards",
     "blurb": "An adjacent concept you might love — bonus, never duty.",
     "path": "/due", "anchor": "serendipity"},
    {"id": "blind-spots", "kind": "feature", "title": "Blind spots",
     "blurb": "Lowest-mastery concepts — study time goes where it matters.",
     "path": "/status", "anchor": "status-blindspots"},
    {"id": "personal-bests", "kind": "feature", "title": "Personal bests",
     "blurb": "Strongest memory, most practiced, sharpest skill — no streaks.",
     "path": "/reviews", "anchor": "bests"},
    # -- Batch 5: eight improvements (I-1 … I-151) --
    {"id": "page-titles", "kind": "improvement", "title": "Unique page titles",
     "blurb": "Every page names its context; browser tabs stay distinct.",
     "path": "/status", "anchor": "status-b5-titles"},
    {"id": "empty-states", "kind": "improvement", "title": "Empty states",
     "blurb": "No dead ends: every dry page offers a next step.",
     "path": "/status", "anchor": "status-b5-empty"},
    {"id": "palette-vars", "kind": "improvement", "title": "Palette variables",
     "blurb": "One :root token source for ink, paper, accents, pass/fail/stale.",
     "path": "/status", "anchor": "status-b5-palette"},
    {"id": "copy-links", "kind": "improvement", "title": "Copy links",
     "blurb": "Every lesson section carries its own deep link.",
     "path": "/status", "anchor": "status-b5-copylink"},
    {"id": "read-progress", "kind": "improvement", "title": "Reading progress",
     "blurb": "A slim bar shows how far through a module page you are.",
     "path": "/status", "anchor": "status-b5-readprogress"},
    {"id": "char-counts", "kind": "improvement", "title": "Char counts",
     "blurb": "Code textareas report chars, lines and words as you type.",
     "path": "/status", "anchor": "status-b5-charcount"},
    {"id": "print-sheet", "kind": "improvement", "title": "Print stylesheet",
     "blurb": "Lessons print cleanly as serif study sheets.",
     "path": "/status", "anchor": "status-b5-printcss"},
    {"id": "answer-guard", "kind": "improvement", "title": "Answer guard",
     "blurb": "Blank submits get an inline warning instead of silence.",
     "path": "/status", "anchor": "status-b5-answerguard"},
    # -- Batch 5: eight features --
    {"id": "session-summary", "kind": "feature", "title": "Session summary",
     "blurb": "Answered, accuracy and what returns when — the debrief.",
     "path": "/status", "anchor": "status-b5-session"},
    {"id": "garden-stages", "kind": "feature", "title": "Garden stages",
     "blurb": "Concepts grow seed to sprout to tree; no streaks.",
     "path": "/status", "anchor": "status-b5-garden"},
    {"id": "cover-colors", "kind": "feature", "title": "Cover colors",
     "blurb": "Each module gets a stable cover hue from its repo hash.",
     "path": "/status", "anchor": "status-b5-cover"},
    {"id": "file-map", "kind": "feature", "title": "File map",
     "blurb": "Breadcrumbs show where a concept sits in the repo tree.",
     "path": "/status", "anchor": "status-b5-filemap"},
    {"id": "prereq-chain", "kind": "feature", "title": "Prereq chain",
     "blurb": "Understand-X-first path with jump links atop each module.",
     "path": "/status", "anchor": "status-b5-prereq"},
    {"id": "exit-ticket", "kind": "feature", "title": "Exit ticket",
     "blurb": "Each lesson ends with one ungraded retrieval question.",
     "path": "/status", "anchor": "status-b5-exitticket"},
    {"id": "misconceptions", "kind": "feature", "title": "Misconceptions",
     "blurb": "Lessons flag the wrong idea learners most often hold.",
     "path": "/status", "anchor": "status-b5-misconceptions"},
    {"id": "lesson-notes", "kind": "feature", "title": "Lesson notes",
     "blurb": "A per-lesson scratchpad kept in your browser only.",
     "path": "/status", "anchor": "status-b5-lessonnotes"},
    # -- Batch 6: eight improvements (I-2 … I-14) --
    {"id": "header-search", "kind": "improvement", "title": "Header search",
     "blurb": "One box in the header searches concepts, modules, and symbols — press / to focus from any page.",
     "path": "/", "anchor": "site-search"},
    {"id": "page-crumbs", "kind": "improvement", "title": "Page breadcrumbs",
     "blurb": "Every nested page opens with its trail — Due, Modules or History first, then module, lesson, card.",
     "path": "/status", "anchor": "status-b6-crumbs"},
    {"id": "level-carry", "kind": "improvement", "title": "Explainer level carries over",
     "blurb": "Pick Plain words once and every link keeps it — the level rides the URL.",
     "path": "/status", "anchor": "status-b6-levelcarry"},
    {"id": "toc-highlight", "kind": "improvement", "title": "Sticky TOC section highlight",
     "blurb": "The sticky module TOC now marks the section you are reading — scroll a module page and watch the current lesson light up.",
     "path": "/modules/{mid}", "anchor": "readtime"},
    {"id": "card-links", "kind": "improvement", "title": "Card deep-links",
     "blurb": "Every History attempt links straight to the exact card on its module page — no more scrolling to find the one you missed.",
     "path": "/reviews", "anchor": "attempts"},
    {"id": "lesson-pager", "kind": "improvement", "title": "Lesson pager",
     "blurb": "Each lesson article ends with previous/next card links — walk a module one card at a time.",
     "path": "/status", "anchor": "status-b6-pager"},
    {"id": "footer-sitemap", "kind": "improvement", "title": "Footer sitemap",
     "blurb": "Every page ends in a grouped site map — Due, Modules, History, About — so no page is a dead end.",
     "path": "/", "anchor": "site-footer"},
    {"id": "scroll-kept", "kind": "improvement", "title": "Keep your place in the queue",
     "blurb": "Answering a card and coming back lands you where you left off, not at the top.",
     "path": "/due", "anchor": "queue"},
    # -- Batch 6: eight features (F-2 … F-9) --
    {"id": "name-that-smell", "kind": "feature", "title": "Name-that-smell",
     "blurb": "Read a real snippet and name its dominant code smell — six smells, one choice.",
     "path": "/status", "anchor": "status-b6-smell"},
    {"id": "rename-exercise", "kind": "feature", "title": "Rename-symbol exercise",
     "blurb": "Propose a clearer name for a weak identifier; convention-checked, rubric-justified.",
     "path": "/status", "anchor": "status-b6-renameex"},
    {"id": "complexity-golf", "kind": "feature", "title": "Complexity golf",
     "blurb": "Rewrite a nested function so it nests less — AST-measured, tests stay green.",
     "path": "/status", "anchor": "status-b6-golf"},
    {"id": "diretro-swap", "kind": "feature", "title": "Dependency-injection swap",
     "blurb": "Rewrite a hardcoded dependency as a parameter; old tests stay green.",
     "path": "/status", "anchor": "status-b6-diretro"},
    {"id": "error-branch", "kind": "feature", "title": "Error-handling retrofit exercises",
     "blurb": "Add the missing error branch: a fault-injection harness fails until your guard handles it. Try one below.",
     "path": "/due", "anchor": "up-next"},
    {"id": "logging-retrofit", "kind": "feature", "title": "Logging-retrofit exercises",
     "blurb": "Type 29 cards mark the lines that deserve a log call — you name each level, checklist-graded with no sandbox.",
     "path": "/status", "anchor": "status-b6-logretro"},
    {"id": "typeanno-retrofit", "kind": "feature", "title": "Type-annotation retrofit",
     "blurb": "Unannotated function in, full annotations out — AST-graded per slot. See how it is judged.",
     "path": "/status", "anchor": "status-b6-typeanno"},
    {"id": "doc-doctest", "kind": "feature", "title": "Doc-example doctest",
     "blurb": "Write a >>> example that passes as a real doctest run.",
     "path": "/status", "anchor": "status-b6-docdoctest"},
    # -- Improvements: the Batch 7 eight --
    {"id": "clickcards-whole-card", "kind": "improvement",
     "title": "Whole-card module links",
     "blurb": "Every module card is one big target with a visible keyboard focus ring.",
     "path": "/status", "anchor": "status-b7-clickcards"},
    {"id": "reviewed-mark", "kind": "improvement",
     "title": "Mark as reviewed",
     "blurb": "Re-read a lesson? Tick it reviewed — no answer, no grade, kept in your browser.",
     "path": "/status", "anchor": "status-b7-reviewed"},
    {"id": "modfilter-tabs", "kind": "improvement",
     "title": "Module status filter",
     "blurb": "The Modules library filters by status — all, in-progress, owned, stale.",
     "path": "/status", "anchor": "status-b7-modfilter"},
    {"id": "modpages-pager", "kind": "improvement",
     "title": "Modules pagination",
     "blurb": "Past 50 modules the library splits into pages — page links keep your filters.",
     "path": "/status", "anchor": "status-b7-modpages"},
    {"id": "chiplinks-chips", "kind": "improvement",
     "title": "Concept chips link to lessons",
     "blurb": "Every concept's status chip jumps straight to its lesson section.",
     "path": "/status", "anchor": "status-b7-chiplinks"},
    {"id": "recent-strip", "kind": "improvement",
     "title": "Recently visited strip",
     "blurb": "Due opens with your last 8 modules — kept in this browser only.",
     "path": "/status", "anchor": "status-b7-recent"},
    {"id": "unsaved-guard", "kind": "improvement",
     "title": "Unsaved-answer guard",
     "blurb": "Start typing an answer and wander off and the browser asks first.",
     "path": "/status", "anchor": "status-b7-unsaved"},
    {"id": "autoscroll-verdict", "kind": "improvement",
     "title": "Result verdict auto-scroll",
     "blurb": "After grading, the verdict block takes focus and scrolls into view.",
     "path": "/status", "anchor": "status-b7-autoscroll"},
    # -- Features: the Batch 7 eight --
    {"id": "proptest-type", "kind": "feature",
     "title": "Property-test authoring",
     "blurb": "State assert invariants for a function — each one runs green or tells you which failed.",
     "path": "/status", "anchor": "status-b7-proptest"},
    {"id": "fuzztriage-type", "kind": "feature",
     "title": "Fuzz-target triage",
     "blurb": "Reproduce a fuzzer-found crash: write the minimal failing call and name the crashing line.",
     "path": "/status", "anchor": "status-b7-fuzztriage"},
    {"id": "perffix-type", "kind": "feature",
     "title": "Perf-fix exercises",
     "blurb": "Rewrite a loop-heavy function so it scores lower — AST-measured, tests stay green.",
     "path": "/status", "anchor": "status-b7-perffix"},
    {"id": "memprofile-type", "kind": "feature",
     "title": "Memory-profile reading",
     "blurb": "Read a tracemalloc-style snapshot and name the top-allocating line.",
     "path": "/status", "anchor": "status-b7-memprofile"},
    {"id": "racehunt-type", "kind": "feature",
     "title": "Race-hunt",
     "blurb": "Spot the shared mutable state: name the line plus the fix — local copy, lock, or parameter.",
     "path": "/status", "anchor": "status-b7-racehunt"},
    {"id": "deadcode-type", "kind": "feature",
     "title": "Dead-code elimination",
     "blurb": "Cut the flagged dead function, branch, or import — remaining tests stay green.",
     "path": "/status", "anchor": "status-b7-deadcode"},
    {"id": "configex-type", "kind": "feature",
     "title": "Config extraction",
     "blurb": "Hoist magic values into named constants; hidden tests stay green.",
     "path": "/status", "anchor": "status-b7-configex"},
    {"id": "apidesign-type", "kind": "feature",
     "title": "API-signature design",
     "blurb": "Design a function signature — name, params with defaults, return annotation.",
     "path": "/status", "anchor": "status-b7-apidesign"},
    # -- Improvements: the Batch 8 eight --
    {"id": "extlinks-distinct", "kind": "improvement",
     "title": "Spot external links at a glance",
     "blurb": "External links now show a marker plus screen-reader note while internal routes and repo paths stay plain.",
     "path": "/status", "anchor": "status-b8-extlinks"},
    {"id": "canonurl-contract", "kind": "improvement",
     "title": "Canonical URL contract",
     "blurb": "One language-prefix-free URL per page — the full route table lives on Status.",
     "path": "/status", "anchor": "status-b8-canonurl"},
    {"id": "originguard-allowlist", "kind": "improvement",
     "title": "Origin allowlist guard",
     "blurb": "?origin back-links only return to known app pages — open-redirect shapes fall back to the queue.",
     "path": "/status", "anchor": "status-b8-originguard"},
    {"id": "buttons-order", "kind": "improvement",
     "title": "Primary button first",
     "blurb": "Every form leads with its primary action — tab order matches visual order.",
     "path": "/status", "anchor": "status-b8-buttons"},
    {"id": "pageids-hooks", "kind": "improvement",
     "title": "Per-page hooks",
     "blurb": "Every page carries a data-page hook from a closed registry — future pages cannot ship unstyled.",
     "path": "/status", "anchor": "status-b8-pageids"},
    {"id": "archived-state", "kind": "improvement",
     "title": "Archived-module notice",
     "blurb": "Deleted modules explain themselves with search and siblings, not a bare 404.",
     "path": "/status", "anchor": "status-b8-archived"},
    {"id": "sitenav-merged", "kind": "improvement",
     "title": "Merged site nav",
     "blurb": "Header and footer render from one nav table — one active state, no drift.",
     "path": "/status", "anchor": "status-b8-sitenav"},
    {"id": "autofocus-answer", "kind": "improvement",
     "title": "Answer-field autofocus",
     "blurb": "Cards focus their answer box as they scroll into view — just start typing.",
     "path": "/status", "anchor": "status-b8-autofocus"},
    # -- Features: the Batch 8 eight --
    {"id": "specwrite-type", "kind": "feature",
     "title": "Spec writing",
     "blurb": "Write acceptance criteria for a function: every checkbox — inputs, returns, edge cases — must appear.",
     "path": "/status", "anchor": "status-b8-specwrite"},
    {"id": "commitmsg-type", "kind": "feature",
     "title": "Commit-message authorship",
     "blurb": "Summarize a diff as a commit message: imperative subject naming the what and the why.",
     "path": "/status", "anchor": "status-b8-commitmsg"},
    {"id": "changelog-type", "kind": "feature",
     "title": "Changelog entry",
     "blurb": "Write a keep-a-changelog entry: pick the Added/Changed/Fixed section and state the user-visible impact.",
     "path": "/status", "anchor": "status-b8-changelog"},
    {"id": "repro-type", "kind": "feature",
     "title": "Issue reproduction",
     "blurb": "Write a minimal repro script from a bug report; the sandbox confirms it fails.",
     "path": "/status", "anchor": "status-b8-repro"},
    {"id": "bisect-type", "kind": "feature",
     "title": "Bisect drill",
     "blurb": "Find the breaking commit in a synthetic history — hash or index.",
     "path": "/status", "anchor": "status-b8-bisect"},
    {"id": "rebase-type", "kind": "feature",
     "title": "Rebase-conflict resolution",
     "blurb": "Resolve a planted git-conflict block keeping both sides; static check stays green.",
     "path": "/status", "anchor": "status-b8-rebase"},
    {"id": "migration-type", "kind": "feature",
     "title": "Migration authoring",
     "blurb": "Rename a record field with a default across fixture rows.",
     "path": "/status", "anchor": "status-b8-migration"},
    {"id": "rollback-type", "kind": "feature",
     "title": "Rollback planning",
     "blurb": "Order the rollback steps for a bad deploy — freeze, flag, revert, verify.",
     "path": "/status", "anchor": "status-b8-rollback"},
    {"id": "collapse-answered", "kind": "improvement",
     "title": "Collapse answered cards",
     "blurb": "Answered Due cards collapse in place with an inline undo button instead of a full reload.",
     "path": "/status", "anchor": "status-b9-collapse"},
    {"id": "five-minute-session", "kind": "improvement",
     "title": "Five-minute session",
     "blurb": "One click queues about five minutes of the most-overdue cards and starts you on them.",
     "path": "/status", "anchor": "status-b9-minisession"},
    {"id": "continue-session", "kind": "improvement",
     "title": "Continue interrupted sessions",
     "blurb": "History rows offer a continue link that rebuilds the queue as it was — cards still due, same module.",
     "path": "/status", "anchor": "status-b9-resume"},
    {"id": "session-share", "kind": "improvement",
     "title": "Shareable session snapshot",
     "blurb": "A link showing one module's answered count and accuracy — read-only, no login, no private data.",
     "path": "/status", "anchor": "status-b9-snapshot"},
    {"id": "link-audit", "kind": "improvement",
     "title": "Quarterly link audit",
     "blurb": "Every internal link the app emits is extracted from rendered HTML and checked against the canonical route table, so broken routes are caught in CI instead of once a quarter by hand.",
     "path": "/status", "anchor": "status-b9-linkcheck"},
    {"id": "dark-mode", "kind": "improvement",
     "title": "Dark mode",
     "blurb": "Dark-OS users get a tested dark palette; every body-text pair passes WCAG AA contrast.",
     "path": "/status", "anchor": "status-b9-darkmode"},
    {"id": "type-scale", "kind": "improvement",
     "title": "Type scale",
     "blurb": "One ratio-based scale for every font size — headings, body, small and code share a single source, not scattered literals.",
     "path": "/status", "anchor": "status-b9-typescale"},
    {"id": "font-stack", "kind": "improvement",
     "title": "Distinctive offline-safe fonts",
     "blurb": "Headings, body, and code each get their own system-font voice — no downloads — with generic-family fallbacks that always render.",
     "path": "/status", "anchor": "status-b9-fontstack"},
    {"id": "threat-model", "kind": "feature",
     "title": "Threat modelling",
     "blurb": "List a function's abuse cases — injections, auth gaps, secrets.",
     "path": "/status", "anchor": "status-b9-threatmodel"},
    {"id": "secret-scan", "kind": "feature",
     "title": "Secret-scan",
     "blurb": "Spot the leaked credential in a snippet — quote the exact value or its line.",
     "path": "/status", "anchor": "status-b9-secretscan"},
    {"id": "input-validation-audit", "kind": "feature",
     "title": "Input-validation audit",
     "blurb": "Spot the inputs that reach dangerous sinks without validation.",
     "path": "/status", "anchor": "status-b9-inputaudit"},
    {"id": "a11y-audit", "kind": "feature",
     "title": "Accessibility audit",
     "blurb": "Spot the access barriers in rendered HTML — missing alt, labels, roles, lang, link names, heading order.",
     "path": "/status", "anchor": "status-b9-a11yaudit"},
    {"id": "i18n-extraction", "kind": "feature",
     "title": "i18n extraction",
     "blurb": "List the hardcoded UI strings to extract for translation — exact set match.",
     "path": "/status", "anchor": "status-b9-i18n"},
    {"id": "regex-authoring", "kind": "feature",
     "title": "Regex authoring",
     "blurb": "Write a regex that matches every required case and rejects the rest — graded on a fixed case-suite.",
     "path": "/status", "anchor": "status-b9-regexex"},
    {"id": "sql-authoring", "kind": "feature",
     "title": "SQL authoring",
     "blurb": "Write a SELECT from a spec — graded on the rows it returns.",
     "path": "/status", "anchor": "status-b9-sqlex"},
    {"id": "css-layout-fix", "kind": "feature",
     "title": "CSS layout fix",
     "blurb": "Fix a broken CSS block to match the wireframe — static tolerant grading.",
     "path": "/status", "anchor": "status-b9-cssfix"},
    {"id": "wordmark-logo", "kind": "improvement",
     "title": "Wordmark logo",
     "blurb": "A single inline SVG lockup (G monogram plus word) in currentColor, so the header mark adapts to every palette including dark mode with no assets and no emoji.",
     "path": "/status", "anchor": "status-b10-wordmark"},
    {"id": "bloom-chip-colors", "kind": "improvement",
     "title": "Bloom chip colors",
     "blurb": "Each Bloom tier has its own chip color in cards, History, and the coach table — scan for weak skills at a glance.",
     "path": "/status", "anchor": "status-b10-bloomchips"},
    {"id": "progress-bar-motion", "kind": "improvement",
     "title": "Animated progress bars",
     "blurb": "Progress bars ease to their new width in 200ms — instant when reduced motion is set.",
     "path": "/status", "anchor": "status-b10-progbar"},
    {"id": "owned-badge-reveal", "kind": "improvement",
     "title": "Owned badge reveal",
     "blurb": "Newly Owned concepts celebrate with a calm quarter-second badge reveal — CSS shapes only, motion-safe.",
     "path": "/status", "anchor": "status-b10-ownedbadge"},
    {"id": "due-card-stagger", "kind": "improvement",
     "title": "Due cards stagger in",
     "blurb": "Queue cards fade up one after another in 35ms steps (245ms total, motion-safe) — pure CSS, no JavaScript.",
     "path": "/status", "anchor": "status-b10-stagger"},
    {"id": "consistent-carets", "kind": "improvement",
     "title": "Consistent disclosure carets",
     "blurb": "Every hint and grading disclosure shares one chevron that rotates open — same affordance in every browser, keyboard and screen-reader behavior unchanged.",
     "path": "/status", "anchor": "status-b10-carets"},
    {"id": "code-line-numbers", "kind": "improvement",
     "title": "Code line numbers",
     "blurb": "Every code block numbers its lines via CSS counters, beside the Copy button it already had.",
     "path": "/status", "anchor": "status-b10-codelines"},
    {"id": "tiny-syntax-highlight", "kind": "improvement",
     "title": "Tiny syntax highlight",
     "blurb": "Python/TS code snippets get dependency-free coloring from a single-pass tokenizer that escapes raw text before wrapping tokens, so markup can never leak.",
     "path": "/status", "anchor": "status-b10-highlight"},
    {"id": "cli-ux-review", "kind": "feature",
     "title": "CLI UX review",
     "blurb": "Spot the one usability flaw in a --help screen — name its category.",
     "path": "/status", "anchor": "status-b10-cliux"},
    {"id": "log-reading", "kind": "feature",
     "title": "Log reading",
     "blurb": "Diagnose an outage from logs alone — name the exact root cause, not a red herring.",
     "path": "/status", "anchor": "status-b10-logread"},
    {"id": "metrics-reading", "kind": "feature",
     "title": "Metrics reading",
     "blurb": "Spot which graph regressed at the deploy mark — reply with its letter.",
     "path": "/status", "anchor": "status-b10-metrics"},
    {"id": "flamegraph-reading", "kind": "feature",
     "title": "Flame-graph reading",
     "blurb": "Spot the frame that dominates a flame graph — name it and say why (widest bar wins).",
     "path": "/status", "anchor": "status-b10-flame"},
    {"id": "crash-triage", "kind": "feature",
     "title": "Crash triage",
     "blurb": "Read a mini traceback — name the crashing function and the fix category.",
     "path": "/status", "anchor": "status-b10-crashdump"},
    {"id": "dep-upgrade", "kind": "feature",
     "title": "Dependency upgrade",
     "blurb": "Migrate a caller across a breaking pin bump — new-API shape in, old shape out.",
     "path": "/status", "anchor": "status-b10-depupgrade"},
    {"id": "license-check", "kind": "feature",
     "title": "License-check",
     "blurb": "Judge whether a dependency fits this AGPL-3.0 project -- verdict plus reason.",
     "path": "/status", "anchor": "status-b10-licensecheck"},
    {"id": "containerize-it", "kind": "feature",
     "title": "Containerize it",
     "blurb": "Write a Dockerfile for a small service — static build gate, no partial credit.",
     "path": "/status", "anchor": "status-b10-containerize"},
    # -- Improvements: Batch 11 reading polish --
    {"id": "hint-tiers", "kind": "improvement",
     "title": "Hint tiers at a glance",
     "blurb": "Hints show their weight: Nudge, Pointer, then Worked step — spend the cheapest help first.",
     "path": "/status", "anchor": "status-b11-hinttiers"},
    {"id": "conf-slider", "kind": "improvement",
     "title": "Segmented confidence slider",
     "blurb": "Rate confidence 1–5 on a tappable segmented control with arrow-key support — same rating, no typing.",
     "path": "/status", "anchor": "status-b11-confslider"},
    {"id": "focus-rings", "kind": "improvement",
     "title": "Focus-visible rings",
     "blurb": "Every link, button, field, and card shows one palette-matched ring the moment you Tab to it.",
     "path": "/status", "anchor": "status-b11-focusrings"},
    {"id": "tap-targets", "kind": "improvement",
     "title": "44px tap targets",
     "blurb": "Every button and input is at least 44px tall — full-size even in compact density.",
     "path": "/status", "anchor": "status-b11-taptargets"},
    {"id": "radius-scale", "kind": "improvement",
     "title": "Unified corner radii",
     "blurb": "Cards round at 12px, controls at 8px, chips pill — one token source, no scattered literals.",
     "path": "/status", "anchor": "status-b11-radius"},
    {"id": "section-spacing", "kind": "improvement",
     "title": "Section spacing rhythm",
     "blurb": "Every section gap comes from one ratio-based scale, so pages breathe evenly.",
     "path": "/status", "anchor": "status-b11-spacing"},
    {"id": "empty-art", "kind": "improvement",
     "title": "Empty-state illustrations",
     "blurb": "Dry pages greet you with a small line illustration above the next step — never a blank wall.",
     "path": "/status", "anchor": "status-b11-emptyart"},
    {"id": "done-hero", "kind": "improvement",
     "title": "Session-complete hero",
     "blurb": "An empty Due queue greets you with a calm all-caught-up banner — celebration, still with a next step.",
     "path": "/status", "anchor": "status-b11-donehero"},
    # -- Features: Batch 11 backend exercises --
    {"id": "cipipe", "kind": "feature",
     "title": "CI pipeline",
     "blurb": "Author a push-triggered CI pipeline — static dry-run lint, no partial credit.",
     "path": "/status", "anchor": "status-b11-cipipe"},
    {"id": "flag-cut", "kind": "feature",
     "title": "Cut the stale flag",
     "blurb": "Remove a dead feature-flag branch — grep gate plus green hidden tests.",
     "path": "/status", "anchor": "status-b11-flagcut"},
    {"id": "backfill-script", "kind": "feature",
     "title": "Backfill script",
     "blurb": "Write a backfill function that migrates old rows to the new shape — sandbox-executed over fixtures.",
     "path": "/status", "anchor": "status-b11-backfill"},
    {"id": "page-the-endpoint", "kind": "feature",
     "title": "Page the endpoint",
     "blurb": "Retrofit paging onto a list endpoint — slices, total, and stable order checked.",
     "path": "/status", "anchor": "status-b11-pageapi"},
    {"id": "cache-invalidation", "kind": "feature",
     "title": "Cache invalidation",
     "blurb": "Name every mutation path that busts a cached value — exact set, no hot-path busts.",
     "path": "/status", "anchor": "status-b11-cacheinv"},
    {"id": "idempotency-double-run", "kind": "feature",
     "title": "Idempotency double-run",
     "blurb": "Make the handler re-runnable — the grader runs it twice and both runs must agree.",
     "path": "/status", "anchor": "status-b11-idempot"},
    {"id": "rate-limit-it", "kind": "feature",
     "title": "Rate-limit it",
     "blurb": "Pick per-key + global limits, a window, burst handling, and 429 + Retry-After — rubric-graded with partial credit.",
     "path": "/status", "anchor": "status-b11-ratelimit"},
    {"id": "webhook-verify", "kind": "feature",
     "title": "Webhook verify",
     "blurb": "Verify an HMAC-signed webhook — valid passes, tampered, wrong-secret, and replayed deliveries rejected.",
     "path": "/status", "anchor": "status-b11-webhook"},
    # -- Improvements: Batch 12 page themes --
    {"id": "logbook-history", "kind": "improvement", "title": "Logbook History",
     "blurb": "History reads like a logbook: monospace dates, ruled rows, muted headers.",
     "path": "/status", "anchor": "status-b12-logbook"},
    {"id": "library-shelf", "kind": "improvement", "title": "Library shelf",
     "blurb": "Module cards stand like books on a shelf — a spine accent in each module's own cover color with a subtle lift.",
     "path": "/status", "anchor": "status-b12-shelf"},
    {"id": "due-briefing", "kind": "improvement", "title": "Due briefing",
     "blurb": "Due cards read as numbered mission cards — queue order needs no markup.",
     "path": "/status", "anchor": "status-b12-briefing"},
    {"id": "verdict-stamps", "kind": "improvement", "title": "Verdict stamps",
     "blurb": "Result verdicts stamp PASS or FAIL in rotated bordered type — plain words, never emoji.",
     "path": "/status", "anchor": "status-b12-verdicts"},
    {"id": "owned-banner", "kind": "improvement", "title": "Owned banner",
     "blurb": "Owned concepts get a calm full-width banner — no confetti, just the milestone.",
     "path": "/status", "anchor": "status-b12-ownbanner"},
    {"id": "press-micro", "kind": "improvement", "title": "Press micro-interactions",
     "blurb": "Buttons and cards press back a touch while you hold them — silent, instant, and still for reduced-motion users.",
     "path": "/status", "anchor": "status-b12-pressfx"},
    {"id": "loading-skeletons", "kind": "improvement", "title": "Loading skeletons",
     "blurb": "Module pages show a static placeholder shell — title, progress, lesson rows — while lessons generate.",
     "path": "/status", "anchor": "status-b12-skeletons"},
    {"id": "optimistic-submit", "kind": "improvement", "title": "Optimistic submit",
     "blurb": "Submit a card and its buttons lock with a spinner and Working status — no double grades while grading runs.",
     "path": "/status", "anchor": "status-b12-optimistic"},
    # -- Features: Batch 12 learning science --
    {"id": "type-contract", "kind": "feature", "title": "Type completeness contract",
     "blurb": "Every exercise type proves six parts — generator, grader, widget, disclosure, emission, e2e answer — audited live below.",
     "path": "/status", "anchor": "status-b12-typecontract"},
    {"id": "delayed-retest", "kind": "feature", "title": "Delayed retest",
     "blurb": "7- and 30-day probe cards resurface owned concepts so recalls measure true retention.",
     "path": "/status", "anchor": "status-b12-retest"},
    {"id": "unlock-quests", "kind": "feature", "title": "Unlock quests",
     "blurb": "Own X to unlock Y — each locked skill shows its unlock path, step by step.",
     "path": "/status", "anchor": "status-b12-quests"},
    {"id": "difficulty-dial", "kind": "feature", "title": "Difficulty dial",
     "blurb": "Tune challenge 1-5 from gentle to spicy — sets how forgotten review cards may be and how many new cards join each short session.",
     "path": "/status", "anchor": "status-b12-diffdial"},
    {"id": "cold-attempt", "kind": "feature", "title": "Cold-attempt sessions",
     "blurb": "Attempt unseen concepts cold before studying — struggle first, then learn.",
     "path": "/status", "anchor": "status-b12-coldattempt"},
    {"id": "worked-fading", "kind": "feature", "title": "Worked-example fading",
     "blurb": "Worked traces fade per concept: full trace, then the last step hides, then only the first shows — recall grows as support shrinks.",
     "path": "/status", "anchor": "status-b12-fading"},
    {"id": "self-explain", "kind": "feature", "title": "Self-explanation prompts",
     "blurb": "Every worked step asks why it exists — explain each line in your own words before moving on.",
     "path": "/status", "anchor": "status-b12-selfexplain"},
    {"id": "elaboration-drills", "kind": "feature", "title": "Elaboration drills",
     "blurb": "Connect a new concept to two you already own — shared tokens pick the partners.",
     "path": "/status", "anchor": "status-b12-elaboration"},
    # -- Improvements: Batch 13 chrome robustness --
    {"id": "error-pages", "kind": "improvement", "title": "Chrome error pages",
     "blurb": "Server errors render inside the normal header and footer with a safe label and a way back — never a naked dropped connection.",
     "path": "/status", "anchor": "status-b13-errpage"},
    {"id": "inline-errors", "kind": "improvement", "title": "Inline form errors",
     "blurb": "Out-of-range answers fail loudly beside the field — a role=alert line naming the fix, not silence.",
     "path": "/status", "anchor": "status-b13-formerr"},
    {"id": "selection-accent", "kind": "improvement", "title": "Selection accent",
     "blurb": "Selected text wears the page accent with ink text — forced-colors users keep native selection.",
     "path": "/status", "anchor": "status-b13-selection"},
    {"id": "palette-scrollbars", "kind": "improvement", "title": "Palette scrollbars",
     "blurb": "Thin palette-matched scrollbars — touch devices and forced-colors users keep natives.",
     "path": "/status", "anchor": "status-b13-scrollbar"},
    {"id": "due-favicon", "kind": "improvement", "title": "Due-count favicon",
     "blurb": "The tab icon carries the live due count as a badge — zero means the plain mark.",
     "path": "/status", "anchor": "status-b13-pageicon"},
    {"id": "share-unfurls", "kind": "improvement", "title": "Share unfurls",
     "blurb": "Shared links unfurl with the page title and lede — no bare URLs, no localhost canonical lie.",
     "path": "/status", "anchor": "status-b13-ogtags"},
    {"id": "density-toggle", "kind": "improvement", "title": "Compact density",
     "blurb": "One header button shrinks gaps and type for small screens — tap targets stay full-size.",
     "path": "/status", "anchor": "status-b13-density"},
    {"id": "responsive-audit", "kind": "improvement", "title": "Responsive audit",
     "blurb": "360/768/1024/1440 audited live over the shipped CSS — phone tables and padding fixed first.",
     "path": "/status", "anchor": "status-b13-responsive"},
    # -- Features: Batch 13 study science --
    {"id": "dual-coding", "kind": "feature", "title": "Dual-coding packs",
     "blurb": "Every key idea gets words plus a diagram plus a worked trace — two channels, one concept.",
     "path": "/status", "anchor": "status-b13-dualcode"},
    {"id": "interleaving", "kind": "feature", "title": "Interleaving engine",
     "blurb": "Practice picks contrast by concept — weakest cell first, never the same idea twice running.",
     "path": "/status", "anchor": "status-b13-interleave"},
    {"id": "spacing-optimizer", "kind": "feature", "title": "Spacing optimizer",
     "blurb": "Per-concept gaps from your own recalls — strong ideas stretch out, fragile ones return tomorrow.",
     "path": "/status", "anchor": "status-b13-spacingopt"},
    {"id": "retrieval-first", "kind": "feature", "title": "Retrieval-first lessons",
     "blurb": "Every lesson asks before it tells — attempt first, then read the explanation.",
     "path": "/status", "anchor": "status-b13-retrieval"},
    {"id": "predict-reveal", "kind": "feature", "title": "Predict-then-reveal",
     "blurb": "Every code snippet hides under a one-click cover — predict first, then reveal.",
     "path": "/status", "anchor": "status-b13-predict"},
    {"id": "conf-scoring", "kind": "feature", "title": "Confidence-weighted scoring",
     "blurb": "Brave-correct beats shy-correct — calibration pays, overconfidence costs.",
     "path": "/status", "anchor": "status-b13-confweight"},
    {"id": "calib-drills", "kind": "feature", "title": "Calibration drills",
     "blurb": "Bet points on answers at explicit odds — fair when honest, profitable only when calibrated.",
     "path": "/status", "anchor": "status-b13-calibdrill"},
    {"id": "overconf-cards", "kind": "feature", "title": "Overconfidence cards",
     "blurb": "Confidence outrunning accuracy by 25 points deals an intervention card with one counter-habit.",
     "path": "/status", "anchor": "status-b13-overconf"},
]

BY_ID = {e["id"]: e for e in ENTRIES}
ORDER = [e["id"] for e in ENTRIES]


def resolve(entry: dict, mid: str = "", lesson: str = "") -> str:
    """Concrete /path#anchor URL for an entry (placeholders filled)."""
    if "{mid}" in entry["path"] and not mid:
        return "/modules"
    path = entry["path"].replace("{mid}", mid).replace("{lesson}", lesson)
    anchor = entry["anchor"].replace("{mid}", mid).replace("{lesson}", lesson)
    return f"{path}#{anchor}" if anchor else path


def step_url(entry_id: str, mid: str = "", lesson: str = "") -> str:
    """Guided-mode URL for one tour step (banner + highlight on arrival)."""
    base = resolve(BY_ID[entry_id], mid, lesson)
    path, sep, frag = base.partition("#")
    join = "&" if "?" in path else "?"
    url = f"{path}{join}tour={entry_id}"
    return f"{url}#{frag}" if sep else url


def context(entry_id: str, mid: str = "", lesson: str = "") -> dict:
    """Banner data for guided mode: position, title, prev/next step URLs."""
    i = ORDER.index(entry_id)
    prev_url = step_url(ORDER[i - 1], mid, lesson) if i > 0 else "/tour"
    next_url = (step_url(ORDER[i + 1], mid, lesson)
                if i + 1 < len(ORDER) else "/tour")
    entry = BY_ID[entry_id]
    return {"id": entry_id, "index": i + 1, "total": len(ORDER),
            "title": entry["title"], "blurb": entry["blurb"],
            "prev_url": prev_url, "next_url": next_url,
            "kind": entry["kind"]}


def targets(db_path: str) -> tuple[str, str]:
    """(latest module id, its first lesson anchor) for tour deep links."""
    from . import db as dbmod
    from . import lessons as lesmod
    con = dbmod.connect(db_path)
    try:
        m = con.execute(
            "SELECT id FROM modules ORDER BY created_at DESC LIMIT 1"
        ).fetchone()
        if m is None:
            return "", ""
        mid = m["id"]
        c = con.execute(
            "SELECT id FROM concepts WHERE module_id=? ORDER BY rowid LIMIT 1",
            (mid,)).fetchone()
    finally:
        con.close()
    if c is None:
        return mid, ""
    node = c["id"].split(":", 1)[1] if ":" in c["id"] else c["id"]
    return mid, f"lesson-{lesmod.slug(node)}"


def page_html(db_path: str) -> str:
    """Catalog of every web-facing item, each with a Show-me link."""
    import html
    mid, lesson = targets(db_path)
    parts = ["<p>Every capability below has a visible home. "
             "<b>Show me</b> jumps to it and highlights it; "
             "Prev/Next walks the whole list.</p>",
             f"<p><a class='btn' href='{step_url(ORDER[0], mid, lesson)}'>"
             "Start guided tour</a></p>"]
    groups = (("mvp", "The loop", "The original learning cycle."),
              ("feature", "Features", "New capabilities, Batch 1."),
              ("improvement", "Improvements", "Batch 1 friction removal."))
    n = 0
    for kind, heading, sub in groups:
        items = [e for e in ENTRIES if e["kind"] == kind]
        lis = []
        for e in items:
            n += 1
            url = step_url(e["id"], mid, lesson)
            lis.append(
                f"<li><b>{n}. {html.escape(e['title'])}</b> — "
                f"{html.escape(e['blurb'])} "
                f"<a class='btn' href='{url}'>Show me</a></li>")
        parts.append(
            f"<h2>{heading}</h2><p><small>{sub}</small></p>"
            f"<ol class='tour-steps' start='{n - len(items) + 1}'>"
            + "".join(lis) + "</ol>")
    return "".join(parts)
